# Generated by Django 3.2.6 on 2021-12-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('empid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('clientName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providerApp.clientmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providerApp.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='createdBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providerApp.usermodel'),
        ),
    ]
