# Generated by Django 3.2 on 2021-12-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='createdBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserModel', to='providerApp.usermodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ClientModel', to='providerApp.usermodel'),
        ),
    ]
