# Generated by Django 3.2 on 2021-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerApp', '0003_auto_20211210_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='createdBy',
            field=models.ManyToManyField(related_name='UserName', to='providerApp.UserModel'),
        ),
    ]
